<?php

namespace AppBundle\Repository;

/**
 * GeoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoRepository extends \Doctrine\ORM\EntityRepository
{
}
