<?php

namespace AppBundle\Repository;

/**
 * image
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository {
  public function findImagesByBook(int $id) {

    $qb = $this->createQueryBuilder('i');
    $qb
      ->innerJoin('i.Books', 'b')
      ->addSelect('b')
      ->where($qb->expr()->in('b.id', $id))
      ->orderBy('i.id', 'DESC')
    ;
    return $qb
      ->getQuery()
      ->getResult()
    ;

  }
}
