<?php

namespace AppBundle\Repository;

/**
 * PictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureRepository extends \Doctrine\ORM\EntityRepository {

    public function findPicturesByBook($id, $maxThumbNbr) {
        $qb = $this->createQueryBuilder('p');
        $qb
          ->Join('p.file', 'f')
          ->Join('p.book', 'b')
          ->Select('p')
          ->where($qb->expr()->in('p.book', $id))
          ->orderBy('f.id', 'DESC')
        ;
//dump($qb->getQuery()->getResult());die();
        return $qb
          ->getQuery()
          ->getResult()
        ;
    }
    
    public function findNewImages() {
        $limit = 100;
        $qb = $this->createQueryBuilder('p');
        $qb
          ->innerJoin('p.file', 'f')
          ->Select('p')
          ->orderBy('f.id', 'DESC')
          ->setMaxResults( $limit );
        ;
        return $qb
          ->getQuery()
          ->getResult()
        ;
  }

    public function findRandomImages() {
        $limit = 100;
        $qb = $this->createQueryBuilder('p');
        $qb
            ->innerJoin('p.file', 'f')
            ->Select('p')
            ->orderBy('RAND()')
            ->setMaxResults( $limit );
        ;
        return $qb
            ->getQuery()
            ->getResult()
        ;
  }

    public function findPopularImages($maxThumbNbr) {
        $limit = $maxThumbNbr;
        $qb = $this->createQueryBuilder('p');
        $qb
          ->Join('p.file', 'f')
          ->Join('p.book', 'b')
          ->Select('p')
          ->orderBy('f.id', 'DESC')
          ->setMaxResults( $limit );
        ;
        return $qb
          ->getQuery()
          ->getResult()
        ;
  }
  
    public function findAjaxImages($bounds, $maxThumbNbr) {
        
        $limit = $maxThumbNbr;
        $qb = $this->createQueryBuilder('p');
        $qb
            ->Join('p.file', 'f')
            ->Join('p.book', 'b')
            ->Select('p')
            ->Where('p.lat IS NOT NULL')
            ->andWhere('p.lng < :east')
            ->andWhere('p.lng > :west')
            ->andWhere('p.lat < :north')
            ->andWhere('p.lat > :south')
            ->orderBy('f.id', 'DESC')
            ->setMaxResults( $limit );
        $qb
            ->setParameters($bounds);
        ;
//dump($qb->getQuery()->getResult());die();
        return $qb
          ->getQuery()
          ->getResult()
        ;
  }
  
    public function findAjax2Images($maxThumbNbr) {
        
        $limit = $maxThumbNbr;
        $qb = $this->createQueryBuilder('p');
        $qb
            ->Join('p.file', 'f')
            ->Join('p.book', 'b')
            ->Select('p')
            ->Where('p.lat IS NOT NULL')
            ->orderBy('f.id', 'DESC')
            ->setMaxResults( $limit );
        ;
dump($qb->getQuery()->getResult());die();
        return $qb
          ->getQuery()
          ->getResult()
        ;
  }
  
    public function findPicturesForAdmin($maxThumbNbr) {
        $limit = $maxThumbNbr;
        $qb = $this->createQueryBuilder('p');
        $qb
          ->Join('p.file', 'f')
          ->Join('p.book', 'b')
          ->Select('p')
          ->orderBy('f.id', 'DESC')
        ;
//dump($qb->getQuery()->getResult());die();
        return $qb
          ->getQuery()
          ->getResult()
        ;
    }


}
