<?php

namespace AppBundle\Repository;

/**
 * talkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class talkRepository extends \Doctrine\ORM\EntityRepository {
    
    public function findMessagesByBook(int $book) {
        $qb = $this->createQueryBuilder('t');
        $qb
          ->innerJoin('t.user', 'u')
          ->Select('t.date')
          ->AddSelect('t.message')
          ->AddSelect('u.username')
          ->where($qb->expr()->in('t.book', $book))
          ->orderBy('t.id', 'DESC')
        ;
        return $qb
          ->getQuery()
          ->getResult()
        ;
    }
    

}
