

#Test:
#  path:     /{req}
#  requirements:
#    req: ".*"
#  defaults: 
#    _controller: AppBundle:Test:view
#
time_view:
  resource: "@AppBundle/Resources/config/routing.yml"
  prefix:   /{_locale}
  requirements:
    _locale: en|fr|de|nl

user:
  resource: "@UserBundle/Resources/config/routing.yml"
  prefix:   /{_locale}
  requirements:
    _locale: en|fr|de|nl


fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"
  prefix:   /{_locale}
  requirements:
    _locale: en|fr|de|nl

fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"
  prefix:   /{_locale}
  requirements:
    _locale: en|fr|de|nl


catchAll:
  path:     /{req}
  requirements:
    req: ".*"
  defaults: 
    _controller: FrameworkBundle:Redirect:urlRedirect
    path: /%locale%/home/popular/
    permanent: true
        
