# app/config/security.yml
security:
  encoders:
    FOS\UserBundle\Model\UserInterface: bcrypt

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: ROLE_ADMIN

  providers:
    fos_userbundle:
      id: fos_user.user_provider.username

  firewalls:
    # disables authentication for assets and the profiler, adapt it according to your needs
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
      pattern: "^/%languages%/"
      provider: fos_userbundle
      form_login:
        login_path: user_security_login 
        check_path: user_security_check
        csrf_token_generator: security.csrf.token_manager
        # if you are using Symfony < 2.8, use the following config instead:
        # csrf_provider: form.csrf_provider
        
        # login success redirecting options (read further below)
        always_use_default_target_path: false
#        default_target_path:            "home"
        target_path_parameter:          _target_path
        use_referer:                    false
        success_handler: user.handler.login_success_handler
        
      logout:
        path: user_security_logout
#        target: /en/home/random/
        success_handler: user.handler.logout_success_handler
      remember_me:
        secret: "%secret%"

  access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: "/admin/", role: ROLE_ADMIN }
    - { path: "^/%languages%/book/$", role: ROLE_USER }
    - { path: "^/%languages%/book/", role: ROLE_USER, methods: [POST, PUT] }
