# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    user.handler.login_success_handler.class: UserBundle\Handler\LoginSuccessHandler
    user.handler.logout_handler.class: UserBundle\Handler\LogoutHandler
    user.handler.logout_success_handler.class: UserBundle\Handler\LogoutSuccessHandler
    account.security_listener.class: UserBundle\Listener\SecurityListener
    
services:
    appbundle.tblprefix_subscriber:
        class: AppBundle\Subscriber\TablePrefixSubscriber
        # set the db table prefix in config
        arguments: [%db.table_prefix%]
        tags:
            - { name: doctrine.event_subscriber }

    user.handler.login_success_handler:
        class:  %user.handler.login_success_handler.class%
        arguments:  ['@router', '@fos_user.user_manager', '@session', '@doctrine.orm.entity_manager']
        tags:
            - { name: 'monolog.logger', channel: 'security' } 
    user.handler.logout_handler:
        class:  %user.handler.logout_handler.class%
        arguments:  ['@router', '@session', '@doctrine.orm.entity_manager']
        tags:
            - { name: 'monolog.logger', channel: 'security' }
    user.handler.logout_success_handler:
        class:  %user.handler.logout_success_handler.class%
        arguments:  ['@router']
        tags:
            - { name: 'monolog.logger', channel: 'security' }
            
    account.security_listener:
        class: %account.security_listener.class%
        arguments: ['@security.authorization_checker', '@security.token_storage', '@session']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }