# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    user.handler.login_success_handler.class: UserBundle\Handler\LoginSuccessHandler
    user.handler.logout_success_handler.class: UserBundle\Handler\LogoutSuccessHandler
    
services:
    appbundle.tblprefix_subscriber:
        class: AppBundle\Subscriber\TablePrefixSubscriber
        # set the db table prefix in config
        arguments: ['%db.table_prefix%']
        tags:
            - { name: doctrine.event_subscriber }

    user.handler.login_success_handler:
        class:  '%user.handler.login_success_handler.class%'
        arguments:  ['@router', '@fos_user.user_manager', '@session', '@doctrine.orm.entity_manager']
        tags:
            - { name: 'monolog.logger', channel: 'security' } 
    user.handler.logout_success_handler:
        class:  '%user.handler.logout_success_handler.class%'
        arguments:  ['@router']
        tags:
            - { name: 'monolog.logger', channel: 'security' }
            
    user.post_persist.listener:
        class: UserBundle\Listener\PrePersistListener
        arguments: []
        tags:
            - { name: doctrine.event_listener, event: prePersist }            

#    user.session.listener:
#        class: UserBundle\Listener\SessionListener
#        arguments: ['@service_container', '@security.token_storage']
#        tags:
#          - { name: kernel.event_listener, event: kernel.request, method: updateSession }
