
ajax_geolocation:
  path: /home/here/
  defaults:
    _controller: AppBundle:Ajax:geolocation
  condition: "request.isXmlHttpRequest()"
  

# Symfony2: URLs with trailing slash and an optional parameter
# http://stackoverflow.com/questions/10091518/symfony2-urls-with-trailing-slash-and-an-optional-parameter
home:
  path: /home/
  defaults: 
    wich: 0
    _controller: AppBundle:Home:view
home_here:
  path: /home/{wich}/
  defaults: 
    _controller: AppBundle:Home:here
  requirements:
    wich: 'here'
wich_home:
  path: /home/{wich}/
  defaults: 
    _controller: AppBundle:Home:view
    
  
search:
  path: /search/
  defaults: 
    _controller: AppBundle:Search:new
  
ajax:
  path: /{item}/{id}/{field}
  defaults: 
    _controller: AppBundle:Ajax:ajax
    _format: json|xml|html
  
book:
  path: /book/{id}/
  defaults: 
    _controller: AppBundle:Book:view
  
bookNew:
  path: /book/
  defaults: 
    _controller: AppBundle:Book:new
  
picture:
  path: /picture/{id}/
  defaults: 
    _controller: AppBundle:Picture:view
