




home:
  path: /home/new/
  defaults: 
    _controller: AppBundle:Home:view
  
wich_home:
  path: /home/{wich}/
  defaults: 
    _controller: AppBundle:Home:view
  
search:
  path: /search/
  defaults: 
    _controller: AppBundle:Search:new
  
ajax:
  path: /{item}/{id}/{field}
  defaults: 
    _controller: AppBundle:Ajax:ajax
    _format: json|xml|html
  
book:
  path: /book/{id}/
  defaults: 
    _controller: AppBundle:Book:view
  
bookNew:
  path: /book/
  defaults: 
    _controller: AppBundle:Book:new
  
picture:
  path: /picture/{id}/
  defaults: 
    _controller: AppBundle:Picture:view
