services:
#    App.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }

    App.beta.html_adder:
        class: AppBundle\Beta\BetaHTMLAdder
        
    App.beta.listener:
        class: AppBundle\Beta\BetaListener
        arguments:
          - "@App.beta.html_adder"
          - "2017-06-01"
        tags:
          - { name: kernel.event_listener, event: kernel.response, method: processBeta }