services:
#    App.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

#    app.locale_listener:
#        class: AppBundle\EventListener\LocaleListener
#        arguments: ['%kernel.default_locale%']
#        tags:
#            - { name: kernel.event_subscriber }
services:
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }