services:
#    App.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }
